sudo scp /home/compassys/LoadTester/parNums0* .
sudo scp /home/compassys/LoadTester/parNums1* .
sudo scp /home/compassys/LoadTester/parNums2* .
sudo scp /home/compassys/LoadTester/parNums3* .
sudo scp /home/compassys/LoadTester/parNums4* .
sudo scp /home/compassys/LoadTester/parNums5* .
sudo scp /home/compassys/LoadTester/parNums6* .
sudo scp /home/compassys/LoadTester/parNums7* .
sudo scp /home/compassys/LoadTester/parNums8* .
sudo scp /home/compassys/LoadTester/parNums9* .
sudo scp /home/compassys/LoadTester/IAT0* .
sudo scp /home/compassys/LoadTester/IAT1* .
sudo scp /home/compassys/LoadTester/IAT2* .
sudo scp /home/compassys/LoadTester/IAT3* .
sudo scp /home/compassys/LoadTester/IAT4* .
sudo scp /home/compassys/LoadTester/IAT5* .
sudo scp /home/compassys/LoadTester/IAT6* .
sudo scp /home/compassys/LoadTester/IAT7* .
sudo scp /home/compassys/LoadTester/IAT8* .
sudo scp /home/compassys/LoadTester/IAT9* .
